version: "3"

services:
  website:
    build: . # uses local dockerfile to build a container
    ports: # expose (device:container) 80:80
      - "80:80"
    restart: unless-stopped # keeps the container running until it is manually stopped
  portainer:
    image: portainer/portainer-ce:latest # clones a container from docker-hub from user: "portainer" named: "portainer-ce" using the "latest" tag
    container_name: portainer # sets a unique user defined name
    restart: unless-stopped
    security_opt: # overwrites security flags
      - no-new-privileges:true # this flag makes sure that the current process or any of its children do not change or gain other capabilities
      # source <https://projectatomic.io/blog/2016/03/no-new-privs-docker/>
    volumes:
      - /etc/localtime:/etc/localtime:ro # read-only, share the time of the host with the container
      - /var/run/docker.sock:/var/run/docker.sock:ro # read-only, share the docker network socket of the host with the container
      - ./portainer-data:/data # full access, shares the data from the local folder "./portainer-data" with the directory "/data"
    ports:
      - 9000:9000
